cookie:
  expiry_days: 30
  key: consciousday_key
  name: consciousday_cookie
credentials:
  usernames:
    demo:
      email: demo@example.com
      failed_login_attempts: 0
      logged_in: false
      name: Demo User
      password: $2b$12$MLrGHo0XcjHbzl.7nYZq1.wezrROz2v.wxC66BHrjPfqILEcsYIyu
      role: admin
    waqar:
      email: waqaras.dev@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Waqar Ahmed
      password: $2b$12$5cYVKA4OEmK9PHv8wvlbM.OsM0aallXKa8eYmVm/7aQsAyOZb.oYK
      role: user
preauthorized:
  emails:
  - demo@example.com
